#define TAPPING_TERM 200
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
#define COMBO_COUNT 20
#define ONESHOT_TAP_TOGGLE 3
#define ONESHOT_TIMEOUT 5000

// To improve mouse keys
#define MOUSEKEY_INTERVAL 12
#define MOUSEKEY_MAX_SPEED 6
#define MOUSEKEY_TIME_TO_MAX 50
#define MOUSEKEY_DELAY 20